[package]
name = "niri_workspaces"
version = "0.1.0"
edition = "2021"
rust-version = "1.87.0"
license = "GPL-3.0-or-later"

[dependencies]
waybar-cffi = "0.1"
niri-ipc = "=25.11.0"
gtk = "0.18"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
